<div id="jr-ps-welcome">
    <div>
        <p><b>Extend and enhance My Private Site with these add-ons. Please visit the Licenses tab to enter license keys
            for premium extensions.</b></p>
    </div>
    <div class="my_private_site_main_admin_grid">
        <div>
            <h3>My Private Site Premium Add-ons</h3>
            All add-ons are backed by an
            unconditional 30-day money-back guarantee.<br><br>
            <a href="https://zatzlabs.com/project/my-private-site-selective-content/">
                <?php echo '<img src="' . dirname(plugin_dir_url(__FILE__)) . '/images/selective-content-extension-420-156.png' . '">'; ?>
            </a>
            <p><A HREF="https://youtu.be/exgJrJJSCNY">Watch the overview video on YouTube</A></p>
            <p>Allow hiding, showing, and obscurifying page content through the use of shortcodes. Can also selectively hide widgets and sidebars.</p><br>
            <a href="https://zatzlabs.com/project/my-private-site-public-pages/">
                <?php echo '<img src="' . dirname(plugin_dir_url(__FILE__)) . '/images/public-pages-extensions-420-156.png' . '">'; ?>
            </a>
            <p><A HREF="https://youtu.be/9WwoF8snNHY">Watch the overview video on YouTube</A></p>
            <p>Allows site operators to designate certain specific pages or pages with specified prefix to be available to the public without login.</p><br>
        </div>
        <div>
            <h3>Helpful WordPress.org Plugins</h3>
            <h3>Authentication Plugins</h3>
            I’m currently testing various authentication plugins with My Private Site 3.0 and will list my favorites here.
            <h3>Custom Login Plugins</h3>
            I’m currently testing various custom login plugins with My Private Site 3.0 and will list my favorites here.
        </div>
        <div>
            <h3>Improve Outgoing Email Reliability</h3>
            Because every WordPress hosting environment is different, the built-in WordPress email capability often is
            somewhat unreliable. The following plugins use external mailing engines and substantially improve mailing
            reliability. Here’s <A
                href="http://www.wpbeginner.com/wp-tutorials/how-to-fix-wordpress-not-sending-email-issue/">a good
            explainer article from WPBeginner</A>.
            <h3><a href="https://wordpress.org/plugins/sendwp/">SendWP</a></h3>
            Hosted mail delivery service. Not free, but they do a lot of the work to ensure delivery.
             <h3><a href="https://wordpress.org/plugins/sendgrid-email-delivery-simplified/">SendGrid</a></h3>
            Send emails through SendGrid from your WordPress installation using SMTP or API integration. The SendGrid
            plugin is used for email delivery on this site.
            <h3><a href="https://wordpress.org/plugins/wpmandrill/">wpMandrill by the MailChimp folks</a></h3>
            The wpMandrill plugin sends emails that are generated by WordPress through Mandrill, a transactional email
            service powered by MailChimp.
            <h3><a href="https://wordpress.org/plugins/wp-mail-smtp/">WP Mail SMTP</a></h3>
            Reconfigures the wp_mail() function to use SMTP instead of mail() and creates an options page to manage the
            settings. 400,00 downloads and 4.7 stars, so it’s definitely a relied-upon solution.
        </div>
    </div>
</div>

